services:
  # =========================
  # NGINX REVERSE PROXY
  # =========================
  nginx:
    image: nginx:alpine
    container_name: smartserve-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    # Dependencies on web, gateway, and auth-server to ensure they are healthy before starting the nginx reverse proxy
    depends_on:
      web:
        condition: service_started
      gateway:
        condition: service_started
      auth-server:
        condition: service_started
    #Network configuration to connect the nginx reverse proxy to the smartserve-net network
    networks:
      - smartserve-net
    restart: unless-stopped
  # =========================
  # REDIS, RABBITMQ, SEQ
  # =========================
  redis:
    image: redis:7-alpine
    container_name: smartserve-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - smartserve-redis-data:/data
    networks:
      - smartserve-net
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: smartserve-rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    volumes:
      - smartserve-rabbitmq-data:/var/lib/rabbitmq
    # healthcheck:
    #   test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 10s
    networks:
      - smartserve-net
    restart: unless-stopped
  seq:
    image: datalust/seq:latest
    container_name: smartserve-seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: ${SEQ_FIRSTRUN_NOAUTHENTICATION:-false}
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_FIRSTRUN_ADMINPASSWORD:-ChangeMe_SeqAdmin_2026!}
    healthcheck:
      disable: true
    ports:
      - ${SEQ_PORT:-5341}:5341
      - ${SEQ_UI_PORT:-5342}:80
    volumes:
      - smartserve-seq-data:/data
    networks:
      - smartserve-net
    restart: unless-stopped
  # =========================
  # SMARTSERVE FRONTEND
  # =========================
  web:
    build:
      context: .
      dockerfile: apps/ResourceryPlatformWeb/Dockerfile
    image: smartserve/web:prod
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s
    # Expose the service on port 80
    expose:
      - "80"
    # Network configuration to connect the web service to the smartserve-net network
    networks:
      - smartserve-net
    restart: unless-stopped
  # =========================
  # AUTH SERVER (OPENIDDICT)
  # =========================
  auth-server:
    build:
      context: .
      dockerfile: apps/ResourceryPlatformWorkflow.AuthServer/Dockerfile
    image: smartserve/auth-server:prod
    # Dependencies on Redis, RabbitMQ, and Seq services to ensure they are healthy before starting the auth-server
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost/health"]
    #     interval: 10s
    #     timeout: 5s
    #     retries: 10
    #     start_period: 30s 
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started

    environment:
      # ASP.NET Core environment and Kestrel settings
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      # OpenIddict application settings
      App__SelfUrl: https://auth.smartserve.ecowas.int
      AuthServer__Authority: https://auth.smartserve.ecowas.int
      App__CorsOrigins: https://smartserve.ecowas.int,https://api.smartserve.ecowas.int,https://auth.smartserve.ecowas.int
      # Database connection strings
      ConnectionStrings__ResourceryPlatformWorkflowAdministrationDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_AdministrationDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowIdentityServiceDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_IdentityServiceDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowSaaSDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_SaaSDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowWorkflowDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_WorkflowDb;Pooling=false;
      # Redis, Seq, and RabbitMQ connection strings
      ConnectionStrings__Redis: ${REDIS_HOST:-smartserve-redis}:${REDIS_PORT:-6379}      
      ConnectionStrings__seq: ${SEQ_URL:-http://smartserve-seq:5341}
      RabbitMQ__Connections__Default__HostName: ${RABBITMQ_HOST:-smartserve-rabbitmq}
      RabbitMQ__Connections__Default__Port: ${RABBITMQ_PORT_INTERNAL:-5672}
      RabbitMQ__Connections__Default__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Connections__Default__Password: ${RABBITMQ_PASSWORD:-guest}
      Serilog__MinimumLevel__Default: Information
      Serilog__WriteTo__Seq__Name: Seq
      Serilog__WriteTo__Seq__Args__serverUrl: http://smartserve-seq:5341
      # OAuth settings
      OAuth__ClientId: ${OAUTH_CLIENT_ID}
      OAuth__ClientSecret: ${OAUTH_CLIENT_SECRET}
      TenantId: ${OAUTH_TENANT_ID}
    # Expose the service on port 80
    expose:
      - 80
    networks:
      - smartserve-net
    restart: on-failure
  # =========================
  # API GATEWAY
  # =========================
  gateway:
    build:
      context: .
      dockerfile: gateway/ResourceryPlatformWorkflow.Gateway/Dockerfile
    image: smartserve/gateway:prod
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s
    #Dependencies on auth-server to ensure it is healthy before starting the gateway
    depends_on:     
      auth-server:
        condition: service_started
    environment:
      # ASP.NET Core environment and Kestrel setting
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      Serilog__MinimumLevel__Default: Information
      Serilog__WriteTo__Seq__Name: Seq
      Serilog__WriteTo__Seq__Args__serverUrl: http://smartserve-seq:5341
    # Expose the service on port 80
    expose:
      - "80"
    # Network configuration to connect the gateway service to the smartserve-net network
    networks:
      - smartserve-net
    restart: unless-stopped
  # =========================
  # MICROSERVICES
  # =========================
  identity-service:
    build:
      context: .
      dockerfile: services/identity/host/ResourceryPlatformWorkflow.IdentityService.HttpApi.Host/Dockerfile
    image: smartserve/identity-service:prod
    # Dependencies on Redis, RabbitMQ, and Seq services to ensure they are healthy before starting the identity-service
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s   
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started
    environment:
      # ASP.NET Core environment and Kestrel settings
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      AuthServer__Authority: https://auth.smartserve.ecowas.int
      AuthServer__MetaAuthority: http://auth-server
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      # Database connection strings
      ConnectionStrings__ResourceryPlatformWorkflowAdministrationDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_AdministrationDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowIdentityServiceDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_IdentityServiceDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowSaaSDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_SaaSDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowWorkflowDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_WorkflowDb;Pooling=false;
      # Redis, Seq, and RabbitMQ connection strings
      ConnectionStrings__Redis: ${REDIS_HOST:-smartserve-redis}:${REDIS_PORT:-6379}      
      ConnectionStrings__seq: ${SEQ_URL:-http://smartserve-seq:5341}
      RabbitMQ__Connections__Default__HostName: ${RABBITMQ_HOST:-smartserve-rabbitmq}
      RabbitMQ__Connections__Default__Port: ${RABBITMQ_PORT_INTERNAL:-5672}
      RabbitMQ__Connections__Default__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Connections__Default__Password: ${RABBITMQ_PASSWORD:-guest}
      Serilog__MinimumLevel__Default: Information
      Serilog__WriteTo__Seq__Name: Seq
      Serilog__WriteTo__Seq__Args__serverUrl: http://smartserve-seq:5341
    # EXpose the service on port 80
    expose:
      - 80
    # Network configuration to connect the identity-service to the smartserve-net network
    networks:
      - smartserve-net
    restart: unless-stopped
  administration-service:
    build:
      context: .
      dockerfile: services/administration/host/ResourceryPlatformWorkflow.Administration.HttpApi.Host/Dockerfile
    image: smartserve/administration-service:prod
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s   
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started
      identity-service:
        condition: service_started
    environment:
      # ASP.NET Core environment
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      App__SelfUrl: https://api.smartserve.ecowas.int
      App__CorsOrigins: https://smartserve.ecowas.int,https://api.smartserve.ecowas.int
      AuthServer__Authority: https://auth.smartserve.ecowas.int
      # Database connection strings
      ConnectionStrings__ResourceryPlatformWorkflowAdministrationDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_AdministrationDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowIdentityServiceDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_IdentityServiceDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowSaaSDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_SaaSDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowWorkflowDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_WorkflowDb;Pooling=false;
      # Redis, Seq, and RabbitMQ connection strings
      ConnectionStrings__Redis: ${REDIS_HOST:-smartserve-redis}:${REDIS_PORT:-6379}
      ConnectionStrings__seq: ${SEQ_URL:-http://smartserve-seq:5341}
      RabbitMQ__Connections__Default__HostName: ${RABBITMQ_HOST:-smartserve-rabbitmq}
      RabbitMQ__Connections__Default__Port: ${RABBITMQ_PORT_INTERNAL:-5672}
      RabbitMQ__Connections__Default__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Connections__Default__Password: ${RABBITMQ_PASSWORD:-guest}
      Serilog__MinimumLevel__Default: Information
      Serilog__WriteTo__Seq__Name: Seq
      Serilog__WriteTo__Seq__Args__serverUrl: http://smartserve-seq:5341
    # Expose the service on port 80
    expose:
      - 80
    networks:
      - smartserve-net
    restart: unless-stopped
  saas-service:
    build:
      context: .
      dockerfile: services/saas/host/ResourceryPlatformWorkflow.SaaS.HttpApi.Host/Dockerfile
    image: smartserve/saas-service:prod
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s
    # Dependencies on Redis, RabbitMQ, Seq, and Identity Service to ensure they are healthy before starting the saas-service
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started
      identity-service:
        condition: service_started
    environment:
      # ASP.NET Core environment and Kestrel settings
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      App__SelfUrl: https://api.smartserve.ecowas.int
      App__CorsOrigins: https://smartserve.ecowas.int,https://api.smartserve.ecowas.int
      AuthServer__Authority: https://auth.smartserve.ecowas.int
      # Database connection strings
      ConnectionStrings__ResourceryPlatformWorkflowAdministrationDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_AdministrationDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowIdentityServiceDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_IdentityServiceDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowSaaSDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_SaaSDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowWorkflowDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_WorkflowDb;Pooling=false;
      # Redis, Seq, and RabbitMQ connection strings
      ConnectionStrings__Redis: ${REDIS_HOST:-smartserve-redis}:${REDIS_PORT:-6379}
      ConnectionStrings__seq: ${SEQ_URL:-http://smartserve-seq:5341}
      RabbitMQ__Connections__Default__HostName: ${RABBITMQ_HOST:-smartserve-rabbitmq}
      RabbitMQ__Connections__Default__Port: ${RABBITMQ_PORT_INTERNAL:-5672}
      RabbitMQ__Connections__Default__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Connections__Default__Password: ${RABBITMQ_PASSWORD:-guest}
      Serilog__MinimumLevel__Default: Information
      Serilog__WriteTo__Seq__Name: Seq
      Serilog__WriteTo__Seq__Args__serverUrl: http://smartserve-seq:5341
    # Expose the service on ports 8080 and 8443
    expose:
      - 80
    networks:
      - smartserve-net
    restart: unless-stopped
  workflow-service:
    build:
      context: .
      dockerfile: services/workflow/host/ResourceryPlatformWorkflow.Workflow.HttpApi.Host/Dockerfile
    image: smartserve/workflow-service:prod
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s   
    # Dependencies on Redis, RabbitMQ, Seq, and Identity Service to ensure they are healthy before starting the workflow-service
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      seq:
        condition: service_started
      identity-service:
        condition: service_started
    environment:
      # ASP.NET Core environment and Kestrel settings
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      App__SelfUrl: https://api.smartserve.ecowas.int
      App__CorsOrigins: https://smartserve.ecowas.int,https://api.smartserve.ecowas.int
      AuthServer__Authority: https://auth.smartserve.ecowas.int
      # Database connection strings
      ConnectionStrings__ResourceryPlatformWorkflowAdministrationDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_AdministrationDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowIdentityServiceDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_IdentityServiceDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowSaaSDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_SaaSDb;Pooling=false;
      ConnectionStrings__ResourceryPlatformWorkflowWorkflowDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_WorkflowDb;Pooling=false;
      # Redis, Seq, and RabbitMQ connection strings
      ConnectionStrings__Redis: ${REDIS_HOST:-smartserve-redis}:${REDIS_PORT:-6379}
      ConnectionStrings__seq: ${SEQ_URL:-http://smartserve-seq:5341}
      RabbitMQ__Connections__Default__HostName: ${RABBITMQ_HOST:-smartserve-rabbitmq}
      RabbitMQ__Connections__Default__Port: ${RABBITMQ_PORT_INTERNAL:-5672}
      RabbitMQ__Connections__Default__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Connections__Default__Password: ${RABBITMQ_PASSWORD:-guest}
      Serilog__MinimumLevel__Default: Information
      Serilog__WriteTo__Seq__Name: Seq
      Serilog__WriteTo__Seq__Args__serverUrl: http://smartserve-seq:5341
    # Expose the service on ports 8080 and 8443
    expose:
      - 80
    # Network configuration to connect the workflow-service to the smartserve-net network
    networks:
      - smartserve-net
    restart: unless-stopped
  migrations:
    build:
      context: .
      dockerfile: shared/ResourceryPlatformWorkflow.DbMigrator/Dockerfile
    image: smartserve/db-migrator:prod
    # Dependencies on Redis, RabbitMQ, Seq, and Identity Service to ensure they are healthy
    profiles:
      - migrations
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__ResourceryPlatformWorkflowAdministrationDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_AdministrationDb;
      ConnectionStrings__ResourceryPlatformWorkflowIdentityServiceDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_IdentityServiceDb;
      ConnectionStrings__ResourceryPlatformWorkflowSaaSDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_SaaSDb;
      ConnectionStrings__ResourceryPlatformWorkflowWorkflowDb: Server=${SQLSERVER_HOST:-host.docker.internal},${SQLSERVER_PORT:-1433};User Id=${SQLSERVER_USER:-sa};Password=${SQLSERVER_PASSWORD:-P@ssw0rd123};TrustServerCertificate=True;Encrypt=False;Database=ResourceryPlatformWorkflow_Production_WorkflowDb;
    restart: on-failure
volumes:
  smartserve-redis-data: null
  smartserve-rabbitmq-data: null
  smartserve-seq-data: null

networks:
  smartserve-net:
    driver: bridge
