// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Transcriptions;

public enum InputSource
{
    Upload = 1,
    Recording = 2
}
