// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Transcriptions;

public interface ITranscriptionAppService : IApplicationService
{
    Task<TranscriptionDto> GetAsync(Guid id);

    Task<List<TranscriptionDto>> GetListAsync();

    Task<TranscriptionDto> CreateAsync(CreateUpdateTranscriptionDto input);

    Task<TranscriptionDto> UpdateAsync(Guid id, UpdateTranscriptionDto input);

    Task DeleteAsync(Guid id);

    Task<TranscriptionDto> GetBySourceReferenceIdAsync(string sourceReferenceId);

    Task<TranscriptionDto> SaveTranscriptAsync(string sourceReferenceId, string transcript);
}
