// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Transcriptions;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITranscriptionAppService), typeof(TranscriptionClientProxy))]
public partial class TranscriptionClientProxy : ClientProxyBase<ITranscriptionAppService>, ITranscriptionAppService
{
    public virtual async Task<TranscriptionDto> GetAsync(Guid id)
    {
        return await RequestAsync<TranscriptionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<TranscriptionDto>> GetListAsync()
    {
        return await RequestAsync<List<TranscriptionDto>>(nameof(GetListAsync));
    }

    public virtual async Task<TranscriptionDto> CreateAsync(CreateUpdateTranscriptionDto input)
    {
        return await RequestAsync<TranscriptionDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateUpdateTranscriptionDto), input }
        });
    }

    public virtual async Task<TranscriptionDto> UpdateAsync(Guid id, UpdateTranscriptionDto input)
    {
        return await RequestAsync<TranscriptionDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateTranscriptionDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<TranscriptionDto> GetBySourceReferenceIdAsync(string sourceReferenceId)
    {
        return await RequestAsync<TranscriptionDto>(nameof(GetBySourceReferenceIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), sourceReferenceId }
        });
    }

    public virtual async Task<TranscriptionDto> SaveTranscriptAsync(string sourceReferenceId, string transcript)
    {
        return await RequestAsync<TranscriptionDto>(nameof(SaveTranscriptAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), sourceReferenceId },
            { typeof(string), transcript }
        });
    }
}
