services:
  identity-server:
    build:
      context: ../../
      dockerfile: apps/ResourceryPlatformWorkflow.AuthServer/Dockerfile
  
  saas-service:
    build:
      context: ../../
      dockerfile: services/saas/host/ResourceryPlatformWorkflow.SaaS.HttpApi.Host/Dockerfile
    depends_on:
      - identity-server