services:
  saas-service:
    build:
      context: ../../
      dockerfile: services/saas/host/ResourceryPlatformWorkflow.SaaS.HttpApi.Host/Dockerfile
    networks:
      - default
      - shared-infra

networks:
  shared-infra:
    external: true
    name: services_default