// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ResourceryPlatformWorkflow.Workflow.Requests;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Requests;

public class CreateUpdateRequestDocumentDto
{
    public string Title { get; set; }

    public string Description { get; set; }

    public string DocumentUrl { get; set; }
}
