// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ResourceryPlatformWorkflow.Workflow.Requests;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Requests;

public interface IRequestAppService : IApplicationService
{
    Task<RequestDto> GetAsync(Guid id);

    Task<List<RequestDto>> GetListAsync();

    Task<List<RequestDto>> GetByStatusAsync(RequestStatus requestStatus);

    Task<List<RequestDto>> GetByUserAsync(Guid userId);

    Task<List<RequestDto>> GetByTypeAsync(RequestType requestType);

    Task<RequestDto> CreateAsync(CreateUpdateRequestDto input);

    Task<RequestDto> UpdateAsync(Guid id, CreateUpdateRequestDto input);

    Task DeleteAsync(Guid id);
}
