// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ResourceryPlatformWorkflow.Workflow.Requests;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Requests;

public enum RequestType
{
    InternalMemorandum = 1,
    IncommingCorrespondence = 2,
    ContributionToReport = 3,
    ConceptNoteTermOfReference = 4,
    Meeting = 5,
    Interpretion = 6,
    Translation = 7,
    GroundTransportation = 8,
    VisaProcurement = 9,
    AccreditationOfHeadsOfMission = 10,
    DiplomaticCocktail = 11,
    ReceptionLodgingOfNewStaff = 12,
    CustomsDutiesWaivers = 13,
    ElectionObservationMission = 14
}
