// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ResourceryPlatformWorkflow.Workflow.Requests;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Requests;

public class RequestDto : FullAuditedEntityDto<Guid>
{
    public RequestType RequestType { get; set; }

    public RequestStatus RequestStatus { get; set; }

    public string DocumentSetUrl { get; set; }

    public RequestDocumentDto[] Documents { get; set; }
}
