// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ResourceryPlatformWorkflow.Workflow.Requests;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Requests;

public enum RequestStatus
{
    Pending = 0,
    Approved = 1,
    Rejected = 2,
    Cancelled = 3
}
