// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ResourceryPlatformWorkflow.Workflow.Requests;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace ResourceryPlatformWorkflow.Workflow.Requests;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IRequestAppService), typeof(RequestClientProxy))]
public partial class RequestClientProxy : ClientProxyBase<IRequestAppService>, IRequestAppService
{
    public virtual async Task<RequestDto> GetAsync(Guid id)
    {
        return await RequestAsync<RequestDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<RequestDto>> GetListAsync()
    {
        return await RequestAsync<List<RequestDto>>(nameof(GetListAsync));
    }

    public virtual async Task<List<RequestDto>> GetByStatusAsync(RequestStatus requestStatus)
    {
        return await RequestAsync<List<RequestDto>>(nameof(GetByStatusAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RequestStatus), requestStatus }
        });
    }

    public virtual async Task<List<RequestDto>> GetByUserAsync(Guid userId)
    {
        return await RequestAsync<List<RequestDto>>(nameof(GetByUserAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), userId }
        });
    }

    public virtual async Task<List<RequestDto>> GetByTypeAsync(RequestType requestType)
    {
        return await RequestAsync<List<RequestDto>>(nameof(GetByTypeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RequestType), requestType }
        });
    }

    public virtual async Task<RequestDto> CreateAsync(CreateUpdateRequestDto input)
    {
        return await RequestAsync<RequestDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateUpdateRequestDto), input }
        });
    }

    public virtual async Task<RequestDto> UpdateAsync(Guid id, CreateUpdateRequestDto input)
    {
        return await RequestAsync<RequestDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CreateUpdateRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
