services:
  identity-server:
    build:
      context: ../..
      dockerfile: apps/ResourceryPlatformWorkflow.AuthServer/Dockerfile
  
  workflow-service:
    build:
      context: ../..
      dockerfile: services/workflow/host/ResourceryPlatformWorkflow.Workflow.HttpApi.Host/Dockerfile
    depends_on:
      - identity-server