services:
  workflow-service:
    build:
      context: ../..
      dockerfile: services/workflow/host/ResourceryPlatformWorkflow.Workflow.HttpApi.Host/Dockerfile
    networks:
      - default
      - shared-infra

networks:
  shared-infra:
    external: true
    name: services_default