version: '3.4'

services:
  identity-server:
    build:
      context: ../../
      dockerfile: templates/service/host/IdentityServerHost/Dockerfile
  
  administration:
    build:
      context: ../../
      dockerfile: templates/service/host/ResourceryPlatformWorkflow.Administration.Host/Dockerfile
    depends_on:
      - identity-server