services:
  identity-server:
    build:
      context: ../../
      dockerfile: apps/ResourceryPlatformWorkflow.AuthServer/Dockerfile
  
  administration-service:
    build:
      context: ../../
      dockerfile: services/administration/host/ResourceryPlatformWorkflow.Administration.HttpApi.Host/Dockerfile
    depends_on:
      - identity-server