services:
  administration-service:
    build:
      context: ../../
      dockerfile: services/administration/host/ResourceryPlatformWorkflow.Administration.HttpApi.Host/Dockerfile
    networks:
      - default
      - shared-infra

networks:
  shared-infra:
    external: true
    name: services_default